# Generated by Django 4.1.4 on 2023-01-16 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                (
                    "job_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry"),
                            ("intern", "Intern"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                        ],
                        max_length=255,
                    ),
                ),
                ("no_of_vacancy", models.IntegerField()),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-time"),
                            ("part-time", "Part-time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                            ("freelance", "Freelance"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "job_location",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("work-from-home", "Work-from-home"),
                            ("office", "Office"),
                        ],
                        max_length=255,
                    ),
                ),
                ("salary_range", models.CharField(max_length=255)),
                ("deadline", models.DateField()),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("experience_required", models.IntegerField(blank=True, null=True)),
                ("skill_required", models.TextField(blank=True, null=True)),
                ("tasks", models.TextField(blank=True, null=True)),
                ("perks_and_benefits", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs_posted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
