# Generated by Django 4.1.4 on 2023-01-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0002_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="name",
            field=models.CharField(default="noob", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="email",
            field=models.EmailField(default="noob@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
