# Generated by Django 4.1.4 on 2023-01-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0003_jobapplication_name_alter_jobapplication_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="job_location",
            new_name="job_nature",
        ),
        migrations.RemoveField(
            model_name="job",
            name="category",
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
