# Generated by Django 4.1.4 on 2023-01-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0004_rename_job_location_job_job_nature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(default="Kathmandu, Nepal", max_length=255),
            preserve_default=False,
        ),
    ]
