# Generated by Django 4.1.4 on 2023-02-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0006_rename_tasks_job_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("Full-time", "Full-time"),
                    ("Part-time", "Part-time"),
                    ("Contract", "Contract"),
                    ("Intern", "Intern"),
                    ("Freelance", "Freelance"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_level",
            field=models.CharField(
                choices=[
                    ("Entry", "Entry"),
                    ("Intern", "Intern"),
                    ("Mid", "Mid"),
                    ("Senior", "Senior"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_nature",
            field=models.CharField(
                choices=[
                    ("Remote", "Remote"),
                    ("Work-from-home", "Work-from-home"),
                    ("Office", "Office"),
                ],
                max_length=255,
            ),
        ),
    ]
