# Generated by Django 4.1.4 on 2023-02-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0007_alter_job_employment_type_alter_job_job_level_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="cover_letter",
            new_name="message",
        ),
    ]
