# Generated by Django 4.1.4 on 2023-02-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0008_rename_cover_letter_jobapplication_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
