# Generated by Django 4.1.4 on 2023-02-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0009_jobapplication_resume"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"ordering": ["-created_at"]},
        ),
    ]
