# Generated by Django 4.1.4 on 2023-02-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0010_alter_jobapplication_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={},
        ),
    ]
