# Generated by Django 4.1.4 on 2024-01-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0011_alter_jobapplication_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("shortlisted", "Shortlisted"),
                    ("interview", "Interview"),
                    ("rejected", "Rejected"),
                    ("hired", "Hired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
