# Generated by Django 4.1.4 on 2024-01-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0012_jobapplication_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobApplication",
        ),
    ]
