# Generated by Django 4.1.4 on 2024-01-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0014_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="education_field_of_study",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
