# Generated by Django 4.1.4 on 2022-12-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
