# Generated by Django 4.1.4 on 2023-01-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0002_alter_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_employer",
            field=models.BooleanField(default=False),
        ),
    ]
