# Generated by Django 4.1.4 on 2023-01-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0003_useraccount_is_employer"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
