# Generated by Django 4.1.4 on 2023-01-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0005_employerprofile_rename_profile_seekerprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seekerprofile",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="seekerprofile",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="seekerprofile",
            name="last_name",
        ),
        migrations.AddField(
            model_name="seekerprofile",
            name="email",
            field=models.EmailField(default="temp@gmail.com", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seekerprofile",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seekerprofile",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seekerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="seekerprofile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
