# Generated by Django 4.1.4 on 2023-01-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0007_rename_phone_seekerprofile_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employerprofile",
            old_name="company_website",
            new_name="website",
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
