# Generated by Django 4.1.4 on 2023-02-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0008_rename_company_website_employerprofile_website_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seekerprofile",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
