# Generated by Django 4.1.4 on 2023-02-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0010_rename_title_seekerprofile_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="seekerprofile",
            name="skills",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
