# Generated by Django 4.1.4 on 2023-02-14 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0011_seekerprofile_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="company",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="seekerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="seeker_profile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
